### ISSUE TITLE
Grafana Loki (Loki) connection hook

### ISSUE THREAD

**Issue by wangobango** [snjypl/airflow-provider-grafana-loki#8]
Could you please specify how to create Grafana Loki (Loki) connection hook in Airflow?

**Comment by snjypl** [comment]
you need to select `Grafana Loki` in connection type. 

![image](https://user-images.githubusercontent.com/4460062/221563666-30a7f7c9-649a-4d46-aca2-563fe8ba636d.png)

in your code if you want to create Loki Hook, you can try below code 

```
 from grafana_loki_provider.hooks.loki import LokiHook
 loki_hook = LokiHook(loki_conn_id=loki_conn_id)

```
